version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=wago_dlm
      - DOCKER_INFLUXDB_INIT_BUCKET=charging_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=3001
      - OCPP_PORT=9000
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=your-super-secret-token
      - INFLUXDB_ORG=wago_dlm
      - INFLUXDB_BUCKET=charging_data
      - MQTT_BROKER_URL=mqtt://mqtt:1883
      - MAX_GRID_CAPACITY_KW=500
      - PEAK_DEMAND_THRESHOLD_KW=450
      - MIN_CHARGING_POWER_KW=3.7
      - MAX_CHARGING_POWER_PER_STATION_KW=22
      - ENERGY_COST_PER_KWH=0.12
      - PEAK_COST_PER_KWH=0.25
      - ENABLE_PV_EXCESS_CHARGING=true
      - ENABLE_LOAD_BALANCING=true
      - PV_SYSTEM_ENABLED=true
      - PV_MAX_CAPACITY_KW=100
      - ENABLE_SCHEDULING=true
    volumes:
      - ./persistence:/app/persistence
      - ./logs:/app/logs
    depends_on:
      - mqtt
      - influxdb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  influxdb-data:
  influxdb-config:
  mqtt-data:
  mqtt-config:
